### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by 2607627233**

### CODE REVIEW

**Review by alexxxdev — CHANGES_REQUESTED** [review]
only res/values-cn/string.xml

**Comment by 2607627233** [comment]
This is my first time to use GitHub
I am not familiar with operation
can i send string.xml to you ?


------------------ 原始邮件 ------------------
发件人: "Alexey Derendyaev"<notifications@github.com>;
发送时间: 2018年9月10日(星期一) 下午3:40
收件人: "syberia-project/platform_packages_apps_SyberiaSettings"<platform_packages_apps_SyberiaSettings@noreply.github.com>;
抄送: "2607627233"<2607627233@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [syberia-project/platform_packages_apps_SyberiaSettings] Chinesetranslation (#30)




@alexxxdev requested changes on this pull request.
 
only res/values-cn/string.xml

**Comment by 2607627233** [comment]
------------------ 原始邮件 ------------------
发件人: "Alexey Derendyaev"<notifications@github.com>;
发送时间: 2018年9月10日(星期一) 下午3:40
收件人: "syberia-project/platform_packages_apps_SyberiaSettings"<platform_packages_apps_SyberiaSettings@noreply.github.com>;
抄送: "2607627233"<2607627233@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [syberia-project/platform_packages_apps_SyberiaSettings] Chinesetranslation (#30)




@alexxxdev requested changes on this pull request.
 
only res/values-cn/string.xml

**Comment by alexxxdev** [comment]
110a973587f83e8ebd275e93b37f8c86d3699b33

**Pull request merged**
